version: '3.8'

services:

  db:
    image: postgres:16
    container_name: lms_db
    restart: always
    environment:
      POSTGRES_DB: lmsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: lms_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DB_NAME: lmsdb
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
